import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import { CartProvider } from '../app/users/contexts/page'; 


const geistSans = localFont({
  src: "./fonts/GeistVF.woff", 
  variable: "--font-geist-sans", 
  weight: "100 900", 
});


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", 
  variable: "--font-geist-mono", 
  weight: "100 900", 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}> {/* Áp dụng phông chữ cho toàn bộ HTML */}
      <body>
        <CartProvider> {/* Bao bọc toàn bộ ứng dụng trong CartProvider để quản lý giỏ hàng */}
          {children} {/* Render các component con */}
        </CartProvider>
      </body>
    </html>
  );
}
